services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspaces/:cached
    command: sleep infinity
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: alga
      DB_PASSWORD: 1234567
      DB_NAME: algatransito
    networks:
      - devnet
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algatransito 
      MYSQL_USER: alga 
      MYSQL_PASSWORD: 1234567
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devnet
    ports:
      - "3306:3306"
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql-data:

networks:
  devnet: