branch-defaults:
  default:
    environment: algatransito-dev
    group_suffix: null
  master:
    environment: null
    group_suffix: null
global:
  application_name: algatransito-dev-api
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  platform_name: null
  platform_version: null
  profile: algaworks
  sc: git
  workspace_type: Application
