services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    profiles:
      - services
      - app
    ports:
      - "3306:3306"
    env_file:
      - .env-app
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - alga-net
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Limita a 50% de uma CPU
          memory: 512M    # Limita a 512MB de memória
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  alga-net:

volumes:
  mysql-data:
