include:
  - docker-compose-network.yml

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env.mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - alga-net
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    tmpfs:
      - /data:size=256m
    networks:
      - alga-net
    restart: on-failure

volumes:
  mysql-data: